__tests__/__fixtures__/fixtures.ts
__tests__/__fixtures__/single-file-pending-updated.json
__tests__/__fixtures__/single-file-pending.json
__tests__/io-test.ts
package.json
src/builders.ts
src/io.ts
yarn.lock

Allows for updating pending items for single files, avoiding the need to regenerate the entire pending list unnecessarily.

Differential update for single files

---

package.json

This ensures that we do a `build` before publishing.

Add prepare script to package.json scripts.

---

__tests__/io-test.ts
src/builders.ts
src/index.ts
src/io.ts

Exposing the `buildPendingLintMessagesMap` function to provide public access to this functionality.

Make pending lint messages map building public

---

__tests__/__fixtures__/ember-template-lint-no-results.json
__tests__/__fixtures__/ember-template-lint-with-errors.json
__tests__/__fixtures__/ember-template-lint-with-warnings.json
__tests__/__fixtures__/eslint-no-results.json
__tests__/__fixtures__/eslint-with-errors.json
__tests__/__fixtures__/eslint-with-warnings.json
__tests__/__fixtures__/existing-batches.json
__tests__/__fixtures__/fixtures.ts
__tests__/__fixtures__/new-batches.json
__tests__/__fixtures__/single-file-no-errors.json
__tests__/__fixtures__/single-file-todo-updated.json
__tests__/__fixtures__/single-file-todo.json
__tests__/__utils__/index.ts
__tests__/__utils__/update-path.ts
__tests__/builders-test.ts
__tests__/io-test.ts
package.json
src/builders.ts
src/io.ts

Currently, lint results (both `eslint` and `ember-template-lint`) return results that include absolute paths for the `filePath` property. Persisting this data would result in the todos being non-deterministic from machine to machine.
This change converts absolute paths to relative paths, enabling us to have true deterministic todo storage.

Ensure we're operating on relative paths vs. absolute

---

__tests__/io-test.ts
package.json
src/index.ts
src/io.ts

The public APIs were using inconsistent parameters. Sometimes they'd use `baseDir`, and some would use `todoStorageDir`. This change realigns the public APIs to ensure they're consistent, which will help with usage.

Aligning APIs for consistency

---

.github/workflows/ci-build.yml
__tests__/io-test.ts
src/builders.ts
src/io.ts

Addresses issue #28: File paths are currently not consistent across different platforms (Posix vs Win32). Per [node's spec](https://nodejs.org/api/path.html#path_windows_vs_posix), to achieve consistent results across platforms we need to use `path.posix` or `path.win32`. Tests should also run on Windows to check for cross platform compatibility issues.

Fixes #28: file path consistency

---

package.json
src/builders.ts
yarn.lock

`posix.relative` was returning an incorrect path for Windows (`../app/app.js` vs `app/app.js`) which was not consistent with the behavior on posix.
It looks like this is an known issue based on the following issues:
- https://github.com/nodejs/node/issues/13887
- https://github.com/nodejs/node/issues/13683
Since `path.relative` works correctly, we just need to normalize the path using the `slash` lib. Also, if the file path is already relative (this happens for `ember-template-lint`) then we can ignore the relative call, preventing the issue cited above.

Fix path for todo data so it's consistent on posix and win32

---

.eslintrc
README.md
package.json
scripts/generate-api-docs.js
src/builders.ts
yarn.lock

Adds a script to auto-generate API docs.
```shell
yarn docs:update
```
This script will
- build the source
- generate the current API docs using jsdoc2md

Auto-generating API docs

---

README.md
__tests__/io-test.ts
src/index.ts
src/io.ts

The `eslint` formatter implementation requires sync APIs (for now). This PR adds related sync APIs in addition to keeping the async ones.

Adding sync APIs and tests

---

__tests__/builders-test.ts
src/builders.ts
src/index.ts

Adds the ability to set `createdDate` for testing purposes, which allows consumers to test due dates functionality.

Adds ability to set due dates created dates for testing

---

__tests__/io-test.ts
package.json
src/io.ts
yarn.lock

The current implementation of todos reads dates as strings. This change ensures they're correctly deserialized back to `Date` objects.

Adding JSON date reviver to deserialize dates

---

__tests__/io-test.ts
src/io.ts

Adds necessary function overloads to `writeTodos[Sync]` implementation, with correct parameter shifting.

Adding overloads for writeTodos[Sync]

---

__tests__/builders-test.ts
src/builders.ts
src/index.ts

This PR fixes the way we provide a static `createdDate` to todos. The [previous PR](https://github.com/ember-template-lint/ember-template-lint-todo-utils/pull/38) that added a test helper that allowed you to set a `createdDate` in module scope seemed reasonable, but didn't work as intended. 
While it's fine to provide the fake dates this way, the two consuming libraries, `@scalvert/eslint-formatter-todo` and `ember-template-lint`, both execute the linting executables via execa when testing. Due to this, it wasn't feasible to provide the `createdDate` to the module scope of that process' todo-utils. Therefore, it was necessary to provide this date via another means. 
Since execa allows you to pass environment variables to its spawned process, this seemed the best approach. As such, this PR …

Changes the way consumers can provide createdDate

---

package.json

Typescript consumers require the `@types/eslint` types to be published with this package to avoid them having to install those types themselves. This PR moves that package from devDependencies to dependencies to facilitate this.

Moves @types/eslint to deps from devDeps

---

README.md
__tests__/builders-test.ts
__tests__/get-severity-test.ts
__tests__/io-test.ts
package.json
scripts/generate-api-docs.js
src/builders.ts
src/get-severity.ts
src/index.ts
src/io.ts
src/types/index.ts
yarn.lock

The PR helps move some of the common behavior needed for todos into this repo. Adds the following functions:
- `getSeverity` - returns the severity based on due date
- `getDatePart` - util for managing consistent UTC dates.

Adds new util `getSeverity`

---

__tests__/get-todo-config-test.ts
src/get-todo-config.ts

The error message for when the `warn` value is greater than or equal to the `error` value specifies that it's related to the `package.json` configuration only, when it in fact works for all. This PR fixes that error to be more accurate.

Fixing error message for invalid config values

---

README.md
__tests__/io-test.ts
src/io.ts
src/types/index.ts

This PR changes the return value of `writeTodos`/`writeTodosSync` to a tuple containing the counts of todos `added` and `removed`. This will allow for this data to be used to output informative messages to the user to indicate what todos were changed during a tool run.

Changes return value of writeTodos[Sync] to return added and removed todo counts

---

__tests__/io-test.ts
src/io.ts

Relates to https://github.com/ember-template-lint/ember-template-lint/issues/1684. If a directory contains no files, we ensure it's deleted. While this does introduce some extra I/O for the removal and potential recreation of the same directory, this does remove ghost directories remaining.

Ensures empty todo directories are deleted

---

__tests__/todo-config-test.ts
docs/spec.md
src/todo-config.ts

We've been using `TODO` and `todo`, depending on the situation. This PR standardizes us using `todo`.

Standardize casing for todos

---

README.md
__tests__/todo-config-test.ts
src/todo-config.ts

Adds new `ensureTodoConfig` directory.
```ts
export function ensureTodoConfig(baseDir: string): void;
```
This allows us to provide this behavior in the respective consuming packages, `@scalvert/eslint-formatter-todo` and `ember-template-lint`.

Adding ensureTodoConfig to write default config

---

README.md
__tests__/io-test.ts
src/io.ts
src/types/index.ts

In order to support use cases from consumers that require skipping the standard behavior of `writeTodos[Sync]`, which is to delete files that no longer have errors represented in the lint results, the signature of those functions have been changed.
```ts
function writeTodosSync(
baseDir: string,
lintResults: LintResult[],
options: WriteTodoOptions = {}
): TodoBatchCounts;
async function writeTodos(
baseDir: string,
lintResults: LintResult[],
options: WriteTodoOptions = {}
): Promise<TodoBatchCounts>
```
Both functions, the sync and async versions, now take an `options` parameter, which uses this interface:
```ts
interface WriteTodoOptions {
filePath?: string;
todoConfig?: TodoConfig;
skipRemoval?: boolean;
}
```
This includes the new option, `skipRemoval`, which allows us to opt-out of …

Changed signature of writeTodos to allow additional param for skipping removal

---

__tests__/io-test.ts
src/io.ts
src/types/index.ts

This PR follows #80 but changes the options that PR added to be more versatile. In this change, instead of using a `skipRemoval` param, we instead provide a `shouldRemove` function that, when evaluated, determines if we should remove todos during batch processing.
This allows us to build out the removal logic with more complex use cases, but delegates the implementation of those use cases to the caller.

Changing property in WriteTodoOptions to more versatile version

---

__tests__/todo-config-test.ts
src/todo-config.ts

The `ensureTodoConfig` API existed so that we could ensure todos had a default daysToDecay set. This ensures that todos are not created and forgotten.
When implementing this, @rwjblue and I realized we could implement a 'lighter touch', one that wouldn't require us to mutate a project's package.json file, which can feel very invasive from a linting tool. Instead, we're not falling back to a default todo config when one is not encountered. The order of precedence is the following, with topmost being used before those below:
- Options in the command line
- Environment variables
- package.json configuration
- defaults 
```json
{
"warn": 30,
"error": 60
}
```
If a consumer wants to 'opt out' of using a todo config entirely, they can set it to an empty object in the package.json.

Returning defaults for todoConfig when none exist

---

__tests__/__fixtures__/eslint-single-error2.json
__tests__/io-test.ts

Ensures that we can scope removals by engine using the `shouldRemove` API.

Adding test to ensure engine scoped removal works using shouldRemove

---

__tests__/__fixtures__/existing-batches.json
__tests__/__fixtures__/new-batches.json
__tests__/date-utils-test.ts
__tests__/io-test.ts
src/builders.ts
src/date-utils.ts
src/get-severity.ts
src/index.ts
src/io.ts

We'd like to be able to support `expired` batches in addition to `add`, `remove`, and `stable`. This allows us to disambiguate which todos are considered expired, and thus effectively no longer useful to track. It also allows consuming apps to be able to delete those `expired` todos easily, without having to determine whether they're expired or not themselves.
We prevented this being a breaking change by adding the `expired` to the end of the tuple, thus widening the API without a backwards incompatible change.

Adding expired batch to getTodoBatches

---

__tests__/__utils__/fake-project.ts
__tests__/builders-test.ts
__tests__/todo-config-test.ts
src/builders.ts
src/todo-config.ts
src/types/index.ts

Implements https://github.com/ember-template-lint/ember-template-lint/issues/1880
This change adds support for using a config file, `.lint-todorc.js`. This config is a superset of the old config, which was simply:
```json
{
"lintTodo": {
"daysToDecay": {
"warn": 5,
"error": 10
}
}
}
```
The new structure adds a level of nesting, allowing you to specify which `engine` the config section applies to:
```json
{
"lintTodo": {
"some-engine": {
"daysToDecay": {
"warn": 5,
"error": 10
},
"daysToDecayByRule": {
"no-bare-strings": { "warn": 10, "error": 20 }
}
}
}
}
```
In addition, you can now configure `daysToDecay` by ruleID, allowing more fine-grained configuration of decay dates. It also provides a single source of truth for configuring those dates.
As of this change, we now support
1. Legacy …

Extends todo configuration to support configuring days to decay by rule ID.

---

src/date-utils.ts

Ensures that the date used by `getDatePart` _is_ always going to be the current UTC date (at 12:00:00). Previously, the date we used was the locale date (e.g. it might be 2021-06-09 in PDT but 2021-06-10 in GMT), which would result in incorrectly flagging expired TODO's.
The fundamental constraint that we are going for here, is that if someone in PDT checks if a todo is expired and at _the exact same time_ someone in IST runs the same test: the results should be the same!

Tweak `getDatePart` to use UTC date

---

README.md
__tests__/todo-config-test.ts
src/todo-config.ts

Adds new API, `validateConfig`, which determines if we have a single valid config.
```ts
export function validateConfig(baseDir: string): ConfigValidationResult;
```
This allows us to check early if a config is unique for a project, and indicate when it's not (with appropriate error message).

Adds new validateConfig function

---

README.md
src/builders.ts
src/io.ts
src/types/index.ts

The current `FilePath` type didn't do a good job at hinting at what this type represented, which isn't exactly a file path, but rather a generated hash for the Todo file path on disc. This update makes it easier to understand the relationship in the Map data structure used throughout the codebase, where the key is the `TodoFileHash`, and the value is the `TodoData`. 
Note: This is part of a number of refactors to transform the code to use fuzzy matching.

Renaming FilePath type to improve code readability

---

.eslintrc
README.md
__tests__/__utils__/build-todo-data.ts
__tests__/__utils__/get-fixture.ts
__tests__/builders-test.ts
__tests__/io-test.ts
__tests__/todo-batch-generator-test.ts
src/builders.ts
src/index.ts
src/io.ts
src/todo-batch-generator.ts
src/todo-matcher.ts
src/types/index.ts

Implements #246 and supersedes #236.
This change adds expanded matching capability on top of the existing exact matching. To disambiguate, the following are differences between the types of matchers:
**Exact match**
Matches on `engine`, `ruleID`, `line`, and `column`.
**Fuzzy match**
Matches on `engine`, `ruleID`, `source`
This enables a looser type of matching for situations when you have edits to a file, and an associated generated todo. Previously, due to the fact that we would always attempt an exact match, if edits occurred that modified the associated line and/or column, we would consider that an expired todo. Now, this affords us more allowance in how we're matching todos, which translates into the user requiring less todo maintenance. 
**Important Notes:**
- we've removed all …

Adding expanded todo batching functionality to account for fuzzy matching

---

src/index.ts

I seem to have deleted the public export of `getTodoBatches`. This PR adds it back.

Adds missing export to public API

---

__tests__/io-test.ts
src/io.ts
src/todo-batch-generator.ts
src/todo-matcher.ts
src/types/todos.ts

We previously used a `Map` not a `Set` in the `remove` batch. Recent updates moved this to a `Set`, since it appeared that we didn't actually need the associated `TodoData` for consumers. This was incorrect, and we actually use the data from the removed todo. 
This change puts it back, which feels nicer in terms of consistency between the batches.

Converts the remove Set back to a Map, which is required for consumers

---

README.md
src/builders.ts
src/index.ts
src/io.ts
src/todo-batch-generator.ts
src/todo-matcher.ts

The `readTodos` API changed to return a Map of TodoMatcher instances. For testing, it's useful to still have an API that reads all todos in a project and returns an array of `TodoDataV2`. This PR adds that, which is used in both dependent projects for testing.

Adds new readTodoData API for convenience reading of TodoDataV2

---

__tests__/__utils__/build-todo-data.ts
__tests__/builders-test.ts
src/todo-batch-generator.ts
src/types/todos.ts

With the advent of fuzzy matching, referencing back to the original lint result was not possible using the [existing](https://github.com/ember-template-lint/ember-template-lint/blob/8a0cde77fbaf2d3ba2f0114e168b414290b3d2c6/lib/-private/todo-handler.js#L73-L79) [logic](https://github.com/scalvert/eslint-formatter-todo/blob/4054d19d830a8bff0ace29ab0ecd6c7d7a341214/src/formatter.ts#L80-L86) for identifying. We needed a way to associate the todo itself with the original lint result, thus providing a deterministic way of finding that lint result in order to mutate the severity, which is the crux of the todo functionality.
This PR adds a new mechanism whereby the consumers pass the lint result identity in when building the todo datum. This allows for referencing the lint result when processing …

Adds match agnostic lint result identity referencing

---

__tests__/io-test.ts
src/io.ts
src/types/todos.ts

This is the last breaking API change of the v10 release. This changes the `TodoBatchCounts` type to return an object with distinctly named properties instead of a tuple of numbers. This adds clarity to the API, and removes the need to return into an unreadable array destructure. 
```ts
export type TodoBatchCounts = {
addedCount: number;
removedCount: number;
stableCount: number;
expiredCount: number;
};
```

Change return value of writeTodos to object

---

README.md
__tests__/__fixtures__/ember-template-lint-with-errors.json
__tests__/builders-test.ts
__tests__/git-operations-test.ts
__tests__/io-test.ts
src/builders.ts
src/io.ts
src/types/todos.ts

The current todos functionality does a reasonably good job of isolating operations between engines. However, during reads, and particularly for those reads that are part of external formatters, this functionality breaks down, as reads are not currently isolated by engines. This can result in inconsistent numbers for projects that are using both `eslint` and `ember-template-lint`, and are also using external formatters that read todo data for display/summarization.
This PR adds the requirement of adding an engine to the reads (via writes), and ensures that this read isolation is working correctly.

Add read options when reading from todo storage file

---

README.md
__tests__/io-test.ts
src/index.ts
src/io.ts

The `getTodoBatches` and `readTodosForFilePath` functions are always used in conjunction to generate the batches. In order to simplify for consumers what they need to call in order to generate batches, this PR adds a new higher-level API that combines some of the lower-level functions.

Adding new API: generateTodoBatches

---

__tests__/__fixtures__/single-file-errors.json
__tests__/__utils__/update-path.ts
__tests__/io-test.ts
package.json
src/builders.ts
src/io.ts
yarn.lock

Fixes https://github.com/ember-template-lint/ember-template-lint/issues/2287

Fixes todos not correctly matching up when using non-normalized relative paths

---

__tests__/builders-test.ts
__tests__/date-utils-test.ts
__tests__/get-severity-test.ts
__tests__/git-operations-test.ts
__tests__/io-test.ts
__tests__/todo-config-test.ts
package.json
src/builders.ts
src/index.ts
src/io.ts
yarn.lock

The logic for the existing `compactTodoStorageFile` function was incorrect. It simply removed `add` operations, but didn't correctly take into consideration that we want to eliminate any `add`/`remove` pairs, resulting in only valid `add` operations. 
This fix addresses that issue, and additionally upgrades vitest to the latest version to avoid a nasty exception during tests.

Fix incorrect logic for todo storage file compacting.

---

package.json
src/todo-config.ts
yarn.lock

When using `find-up`, since this project is cjs and is published as such, there's a conflict with the published package when compiled into a `require` statement. Requiring the `find-up` package doesn't work, so downgrading it was the most simple solution to this.
Future efforts will convert this package to multi-target esm/cjs publishing.

Downgrading find-up as it collides with other projects using ESM

---

src/builders.ts
src/io.ts
src/types/todos.ts
tests/io-test.ts

Let's try this again...
Fixing compacting to not eagerly delete other engine's entries in the `.lint-todo` file.

Fix compacting to not be destructive with other engines

---

README.md
package.json
src/index.ts
src/source.ts
tests/source-test.ts

Adds 3 new utils for extracting source file contents and fragments from the underlying source files. This is useful for consumers who are integrating todos into third-party tools that have no source extracted as part of their returned results.
Source fragments are a necessary part of the fuzzy matching algorithm, where we attempt to run matches to identify todos.

Adding utils to read and extract source fragments

---

src/builders.ts
src/io.ts
tests/builders-test.ts
tests/io-test.ts

I've been seeing this issue for a very long time, so thought I'd contribute a fix.
This PR ensures that compact-todo writes an EOL at the end of the file.
It also adds several tests for existing functions
---
Fixes an issue where running compact todo would always result in a file that is missing an EOL at the end. This then compounds into further issues, - if you then later update the todo file (or some other task that appends) then you end up with a doubled-operation line like this
(scroll along to see the two ops on the same line)
```
add|ember-template-lint|no-bare-strings|9|11|9|11|1075c086b703df3b01e8d6013dae65668d6d865d|1690848000000|||app/components/charts/dashboard/awards-earned/trophy/template.hbsadd|ember-template-lint|no-bare-strings|14|11|14|11|6d12c8adbefeaeacac0d48274df3a195c …
```

Fix compact todo EOL issues, add more tests
